### ISSUE TITLE
游戏中在线下载的数据文件名时间不对

### ISSUE THREAD

**Issue by forgot-passwd** [Webster-jx3/JH#16]
在游戏中在下载回来的文件名时间为19700101_08.00

DBM_Remote-zhcn-55-19700101_08.00.jx3dat

导致新的数据没法下载来，一直都是旧数据

**Comment by forgot-passwd** [comment]
还有一个问题是在网站下载台服版本没有转码成繁体。

**Comment by luckyyyyy** [comment]
服务器少返回一个dateline 晚点处理
