### ISSUE TITLE
DBM倒计时条还有问题

### ISSUE THREAD

**Issue by Dearest** [Webster-jx3/JH#3]
比如 第一次先监控到了洛道刷马的公告，这时候出现了（马驹倒计时）倒计时条。飞到洛道地图之后，监控到了洛道的马被抓，这时如果设置了一个相同唯一性ID的（马驹被抓）倒计时条，就应该出现马驹被抓倒计时条顶替之前的马驹倒计时条。但是在上一次更新之后，就不会出现顶替了。即在同一个地图唯一性ID不起作用

**Comment by luckyyyyy** [comment]
把设置都发给我看下 截图

**Comment by luckyyyyy** [comment]
这个问题 应该是上次我修复了一个逻辑后造成的遗留问题 其实也不能算遗留问题
插件处理普通倒计时和分段倒计时的区别
普通倒计时：UI上的时间填写是数字，不是XX,XX;。
分段倒计时：UI上的时间填写的是XX,XX;的形式。

插件内部处理逻辑是一样的，唯一的区别是，分段倒计时会增加一个默认最大防刷新时间，这个时间可以去掉，留空的话默认是最大时间，如果不需要的话直接写0，是这个原因造成的。

**Comment by Dearest** [comment]
我将倒计时条上的 UI上最后那里填了0，但是后一个相同唯一ID的倒计时条依然不会顶替前一个，我回去再测试下是不是后一个倒计时条没有触发

**Comment by luckyyyyy** [comment]
可以再试试，不行反馈给我，谢谢。

**Comment by Dearest** [comment]
确认是分段倒计时最大防刷新时间没有设置好，我设置为0之后就正常了
